local UrlActions = require('modules/UrlActions')
local AppWindowManager = require('modules/AppWindowManager')
local Dashboard = require('modules/Dashboard')
local ShowJoe = require('modules/ShowJoe')
local TomatoTimer = require('modules/TomatoTimer')

UrlActions:init()
AppWindowManager:init()
Dashboard:init()
ShowJoe:init()
TomatoTimer:init()